name: telebalt
description: A telegram bot that interacts with cobalt API
version: 1.0.0
repository: https://github.com/im-trisha/telebalt

environment:
  sdk: ^3.7.0

dependencies:
  dio: ^5.8.0+1
  path: ^1.9.1
  drift: ^2.25.1

  slang: ^4.5.0
  dotenv: ^4.2.0
  talker: ^4.6.14
  televerse: ^2.3.0
  dart_dotenv: ^1.0.1

  # Annotations for generators
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  riverpod: ^2.6.1
  format: ^1.6.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15

  # Generators
  freezed: ^3.0.0
  build_runner: ^2.4.15
  retrofit_generator: ^9.1.9
  json_serializable: ^6.9.4
  drift_dev: ^2.25.2
