import 'package:format/format.dart';
import 'package:telebalt/bot/common/context.dart';
import 'package:telebalt/bot/common/handle_url.dart';
import 'package:telebalt/bot/common/utils.dart';
import 'package:telebalt/consts.dart';
import 'package:telebalt/services/local/database/database.dart';
import 'package:telebalt/services/network/network.dart';
import 'package:televerse/telegram.dart' as tg;
import 'package:televerse/televerse.dart';

part 'handlers/on_message.dart';
part 'handlers/promote.dart';
part 'handlers/my_chat_member.dart';
part 'handlers/start.dart';
part 'handlers/help.dart';
part 'handlers/on_error.dart';
part 'handlers/nickname.dart';
part 'handlers/status.dart';
part 'handlers/users.dart';
part 'handlers/chats.dart';
part 'handlers/on_inline_query.dart';
